// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Unlit/TextureLine" {
    Properties{
     _MainTex("Base (RGB)", 2D) = "white" { }
    }
        SubShader{
         LOD 100
         Tags { "RenderType" = "Opaque" }


        // Stats for Vertex shader:
        //        d3d11: 9 math
        // Stats for Fragment shader:
        //        d3d11: 0 math, 1 texture
        Pass {
         Tags { "RenderType" = "Opaque" }
         //////////////////////////////////
         //                              //
         //      Compiled programs       //
         //                              //
         //////////////////////////////////
       //////////////////////////////////////////////////////
       Global Keywords : <none>
       Local Keywords : <none>
       --Hardware tier variant : Tier 1
       --Vertex shader for "d3d11" :
        // Stats: 9 math, 2 temp registers
        Uses vertex data channel "Vertex"
        Uses vertex data channel "TexCoord0"

        Constant Buffer "$Globals" (48 bytes) on slot 0 {
          Vector4 _MainTex_ST at 32
        }
        Constant Buffer "UnityPerDraw" (176 bytes) on slot 1 {
          Matrix4x4 unity_ObjectToWorld at 0
        }
        Constant Buffer "UnityPerFrame" (368 bytes) on slot 2 {
          Matrix4x4 unity_MatrixVP at 272
        }

        Shader Disassembly :
        //
        // Generated by Microsoft (R) D3D Shader Disassembler
        //
        //
        // Input signature:
        //
        // Name                 Index   Mask Register SysValue  Format   Used
        // -------------------- ----- ------ -------- -------- ------- ------
        // POSITION                 0   xyzw        0     NONE   float   xyz 
        // TEXCOORD                 0   xy          1     NONE   float   xy  
        //
        //
        // Output signature:
        //
        // Name                 Index   Mask Register SysValue  Format   Used
        // -------------------- ----- ------ -------- -------- ------- ------
        // SV_POSITION              0   xyzw        0      POS   float   xyzw
        // TEXCOORD                 0   xy          1     NONE   float   xy  
        //
              vs_4_0
              dcl_constantbuffer CB0[3], immediateIndexed
              dcl_constantbuffer CB1[4], immediateIndexed
              dcl_constantbuffer CB2[21], immediateIndexed
              dcl_input v0.xyz
              dcl_input v1.xy
              dcl_output_siv o0.xyzw, position
              dcl_output o1.xy
              dcl_temps 2
           0: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
           1 : mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
           2 : mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
           3 : add r0.xyzw, r0.xyzw, cb1[3].xyzw
           4 : mul r1.xyzw, r0.yyyy, cb2[18].xyzw
           5 : mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
           6 : mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
           7 : mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
           8 : mad o1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
           9 : ret
                  // Approximately 0 instruction slots used


                  -- Hardware tier variant : Tier 1
                  --Fragment shader for "d3d11" :
                  // Stats: 0 math, 1 temp registers, 1 textures
                  Set 2D Texture "_MainTex" to slot 0

                  Shader Disassembly :
              //
              // Generated by Microsoft (R) D3D Shader Disassembler
              //
              //
              // Input signature:
              //
              // Name                 Index   Mask Register SysValue  Format   Used
              // -------------------- ----- ------ -------- -------- ------- ------
              // SV_POSITION              0   xyzw        0      POS   float       
              // TEXCOORD                 0   xy          1     NONE   float   xy  
              //
              //
              // Output signature:
              //
              // Name                 Index   Mask Register SysValue  Format   Used
              // -------------------- ----- ------ -------- -------- ------- ------
              // SV_Target                0   xyzw        0   TARGET   float   xyzw
              //
                    ps_4_0
                    dcl_sampler s0, mode_default
                    dcl_resource_texture2d(float,float,float,float) t0
                    dcl_input_ps linear v1.xy
                    dcl_output o0.xyzw
                    dcl_temps 1
                 0: sample r0.xyzw, v1.xyxx, t0.xyzw, s0
                 1 : mov o0.xyz, r0.xyzx
                 2 : mov o0.w, l(1.000000)
                 3 : ret
                        // Approximately 0 instruction slots used


                         }
    }
}